//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atribute
    {
        public int id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<byte> deleted { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<int> parent { get; set; }
    }
}
