//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atributes_type
    {
        public int id { get; set; }
        public Nullable<int> atributes_id { get; set; }
        public string type { get; set; }
        public string default_value { get; set; }
        public Nullable<byte> required { get; set; }
        public string apply_to { get; set; }
        public Nullable<byte> comparable { get; set; }
        public Nullable<byte> validate { get; set; }
    }
}
