//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beeshopEntities : DbContext
    {
        public beeshopEntities()
            : base("name=beeshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<atribute> atributes { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer_group> customer_group { get; set; }
        public DbSet<manufacture> manufactures { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<products_atributes> products_atributes { get; set; }
        public DbSet<products_crosssell> products_crosssell { get; set; }
        public DbSet<products_data> products_data { get; set; }
        public DbSet<products_group_price> products_group_price { get; set; }
        public DbSet<products_image> products_image { get; set; }
        public DbSet<products_inventory> products_inventory { get; set; }
        public DbSet<products_price> products_price { get; set; }
        public DbSet<products_related> products_related { get; set; }
        public DbSet<products_review> products_review { get; set; }
        public DbSet<products_special_price> products_special_price { get; set; }
        public DbSet<products_upsell> products_upsell { get; set; }
    }
}
