//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> group_id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string tax_vat_number { get; set; }
        public string gender { get; set; }
        public string password { get; set; }
    }
}
