//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public Nullable<int> atributes_group_id { get; set; }
        public string name { get; set; }
        public string short_des { get; set; }
        public string des { get; set; }
        public string sku { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<byte> status { get; set; }
        public string url_key { get; set; }
        public string manufacture { get; set; }
        public string country_of_manufacture { get; set; }
        public string tags { get; set; }
        public Nullable<System.DateTime> as_new_from_date { get; set; }
        public Nullable<System.DateTime> as_new_to_date { get; set; }
        public Nullable<int> viewed { get; set; }
        public Nullable<System.DateTime> date_edit { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
