//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_data
    {
        public int id { get; set; }
        public string SKU { get; set; }
        public string UPC { get; set; }
        public string EAN { get; set; }
        public string JAN { get; set; }
        public string ISBN { get; set; }
        public string MPN { get; set; }
        public Nullable<double> Length { get; set; }
        public string LengthClass { get; set; }
        public Nullable<double> Weight { get; set; }
        public string WeightClass { get; set; }
        public Nullable<double> Height { get; set; }
        public string LinkWeb { get; set; }
    }
}
