//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_promotion_rule
    {
        public int id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<int> fromdate { get; set; }
        public Nullable<int> todate { get; set; }
        public Nullable<byte> is_active { get; set; }
        public Nullable<byte> all_product { get; set; }
        public Nullable<byte> type_action { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
    }
}
