//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_sales_rule_customer_group
    {
        public long id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public Nullable<int> customer_group_id { get; set; }
    }
}
