//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_image_media
    {
        public long id { get; set; }
        public Nullable<int> products_id { get; set; }
        public string value { get; set; }
        public string label { get; set; }
        public Nullable<byte> sort_order { get; set; }
        public Nullable<byte> thumb_nail { get; set; }
        public Nullable<byte> small_image { get; set; }
        public Nullable<byte> base_image { get; set; }
        public Nullable<byte> is_video { get; set; }
        public Nullable<byte> is_youtube { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
