//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_review
    {
        public long id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string author { get; set; }
        public string des { get; set; }
        public Nullable<byte> rating { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
