//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_promotion_rule_condition
    {
        public long id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public Nullable<int> products_id { get; set; }
        public string field_name { get; set; }
        public string condition { get; set; }
        public string value { get; set; }
    }
}
