//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_price
    {
        public long id { get; set; }
        public Nullable<int> products_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> group_price_id { get; set; }
        public Nullable<int> special_price_id { get; set; }
        public Nullable<double> manufacture_price_retail { get; set; }
        public Nullable<byte> tax_class { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
