//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_rule_coupon
    {
        public int id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public string code { get; set; }
        public Nullable<int> limited { get; set; }
        public Nullable<int> times_useds { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<byte> type { get; set; }
    }
}
