//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order_item
    {
        public long id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> parent_item_id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public Nullable<int> products_id { get; set; }
        public string products_type { get; set; }
        public string sku { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> tax_percent { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> row_total { get; set; }
        public string status { get; set; }
        public Nullable<decimal> qty_ordered { get; set; }
        public Nullable<decimal> qty_canceled { get; set; }
        public Nullable<decimal> qty_shipped { get; set; }
    }
}
