//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order
    {
        public long id { get; set; }
        public string state { get; set; }
        public string status { get; set; }
        public string coupon_code { get; set; }
        public string protect_code { get; set; }
        public string shipping_des { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string from_ip { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string payment_method { get; set; }
        public string shipping_method { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> shipping_fee { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> paid_total { get; set; }
        public Nullable<decimal> refunded_total { get; set; }
        public Nullable<decimal> due_total { get; set; }
    }
}
