//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoice_item
    {
        public long id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> order_item_id { get; set; }
        public Nullable<int> products_id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> row_total { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string des { get; set; }
        public string sku { get; set; }
    }
}
