//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_invoice
    {
        public long id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> shipping_amount { get; set; }
        public Nullable<decimal> subtotal_incl_tax { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> total_qty { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<int> billing_address_id { get; set; }
        public Nullable<int> shipping_address_id { get; set; }
        public Nullable<byte> email_sent { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string des { get; set; }
    }
}
