//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_rate
    {
        public int id { get; set; }
        public Nullable<int> geo_zone_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> rate { get; set; }
    }
}
